[package]
name = "slab_tree"
version = "0.1.0"
authors = ["Ian <iwburns8@gmail.com>"]
description = "A vec-backed tree structure with tree-specific generational indexes."
license = "MIT"

[dependencies]
snowflake = "1.3.0"
